# Generated by Django 5.1.15 on 2026-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(blank=True, max_length=200)),
                (
                    "start_date",
                    models.CharField(
                        blank=True, help_text="e.g. 2021 or Sep 2021", max_length=20
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        default="Present",
                        help_text="e.g. 2025 or Present",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
